[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
chrono = "0.4.38"
reqwest = {version = "0.12.9", default-features = false, features = ["rustls-tls", "blocking"]}